# Generated by Django 6.0 on 2025-12-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='rent', help_text='Defines whether property is for SALE or RENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_size_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent (used when category = rent)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price (used when category = sale)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('land', 'Land'), ('house', 'House'), ('apartment', 'Apartment'), ('room', 'Room'), ('office', 'Office')], default='house', max_length=20),
        ),
    ]
