# Generated by Django 6.0 on 2025-12-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_category_alter_property_land_size_sqm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Stable key (e.g. wifi, kitchen, paid_parking)', max_length=60, unique=True)),
                ('name', models.CharField(help_text='Human friendly name (e.g. Wi-Fi, Kitchen)', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('icon', models.CharField(blank=True, help_text='Optional icon identifier for client UI', max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, help_text='Highlight/featured property'),
        ),
        migrations.AddField(
            model_name='property',
            name='facilities',
            field=models.ManyToManyField(blank=True, help_text='Select facilities/amenities for this property', related_name='properties', to='core.facility'),
        ),
    ]
