# Generated by Django 5.2.9 on 2026-01-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='properties/thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='facility',
            name='key',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
